In [43]:
import numpy as np
import pandas as pd
from sklearn import model_selection, datasets, metrics, tree


In [21]:
# пункт 0
digit = datasets.load_digits()

In [5]:
from pandas import DataFrame

In [22]:
digit.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [39]:
digit.target

array([5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7, 7, 3, 5, 1, 0, 0, 2, 2, 7, 8, 2,
       0, 1, 2, 6, 3, 3, 7, 3, 3, 4, 6, 6, 6, 4, 9, 1, 5, 0, 9, 5, 2, 8,
       2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4, 6, 3, 1, 3, 9, 1, 7, 6, 8, 4, 3,
       1, 4, 0, 5, 3, 6, 9, 6, 1, 7, 5, 4, 4, 7, 2, 8, 2, 2, 5, 7, 9, 5,
       4, 8, 8, 4, 9, 0, 8, 9])

In [24]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
digit.data.shape

(1797, 64)

In [26]:
digits = DataFrame(digit.data)
digits['target'] = digit.target

In [27]:
digits.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  target  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

In [28]:
digits.shape

(1797, 65)

In [41]:
X = digit.data
y = digit.target

In [50]:
import sklearn

In [64]:
# пункт 1
clf = tree.DecisionTreeClassifier(random_state=0)
scores = model_selection.cross_val_score(clf, X, y, cv = 10)

In [65]:
scores.mean()

0.8241247672253259

In [55]:
with open('1.txt','w') as f:
    f.write(str(scores.mean()))

In [68]:
# пункт 2
from sklearn.ensemble import BaggingClassifier

In [70]:
bg = BaggingClassifier(base_estimator = clf, n_estimators = 100, random_state = 0)
scores_bg = model_selection.cross_val_score(bg, X, y, cv = 10)
scores_bg.mean()

0.9253786468032278

In [71]:
with open('2.txt','w') as f:
    f.write(str(scores_bg.mean()))

In [75]:
# пункт 3
bg_d = BaggingClassifier(base_estimator = clf, n_estimators = 100, random_state = 0, max_features=int(np.sqrt(X.shape[1])))
scores_bg_d = model_selection.cross_val_score(bg_d, X, y, cv = 10)
scores_bg_d.mean()

0.9304283054003726

In [76]:
with open('3.txt','w') as f:
    f.write(str(scores_bg_d.mean()))


In [77]:
# пункт 4
clf_4 = tree.DecisionTreeClassifier(random_state=0, max_features=int(np.sqrt(X.shape[1])))
bg_d = BaggingClassifier(base_estimator = clf_4, n_estimators = 100, random_state = 0)
scores_bg_d = model_selection.cross_val_score(bg_d, X, y, cv = 10)
scores_bg_d.mean()

0.9510211049037863

In [78]:
with open('4.txt','w') as f:
    f.write(str(scores_bg_d.mean()))

In [82]:
clf_random = ensemble.RandomForestClassifier(n_estimators = 100,  random_state = 0)
train_sizes, train_scores, test_scores = model_selection.learning_curve(clf_random, X, y, cv=10, scoring='accuracy')
print(train_sizes)
print(train_scores.mean(axis = 1))
print(test_scores.mean(axis = 1))

[ 161  525  889 1253 1617]
[1. 1. 1. 1. 1.]
[0.77685599 0.89705773 0.92930168 0.9326288  0.94657666]
